name = "meet-sig"
main = "src/worker.ts"
compatibility_date = "2025-01-01"

[placement]
mode = "smart"

[[durable_objects.bindings]]
name = "ROOMS"
class_name = "Room"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["Room"]
